#:schema node_modules/wrangler/config-schema.json
name = "hono-tutorial"
main = "src/index.ts"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "todo-api-drizzle"
database_id = "a5dc59f0-ff2b-49c5-b071-b567b72ee53d"
migrations_dir = "drizzle/migrations"
